### ISSUE TITLE
R36S - won`t start

### ISSUE THREAD

**Issue by Vendo233** [JeodC/PortMaster-2Ship2Harkinian#1]
log

./2s2h.elf: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /roms/ports/soh2/libs/libzip.so.4)
./2s2h.elf: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /roms/ports/soh2/libs/libcrypto.so.3)
./2s2h.elf: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /roms/ports/soh2/libs/libcrypto.so.3)

update to latest arkOS 5.24 did not help

PS: SOH works on this device

**Comment by AeolusUX** [comment]
I don't think this has worked before.

**Comment by JeodC** [comment]
The library files provided require newer glibc. I will have to procure versions for arkos.

**Comment by JeodC** [comment]
Please try this again.

**Comment by Vendo233** [comment]
works! thank you @JeodC
